"""add_user_daily_and_radar_recommendations

Revision ID: 011206312bcb
Revises: c0eb926fd655
Create Date: 2026-06-13 17:22:23.398073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '011206312bcb'
down_revision: Union[str, Sequence[str], None] = 'c0eb926fd655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_recommendations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('music_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_daily_recommendations')
    )
    op.create_index('idx_user_daily_recommendations_date', 'user_daily_recommendations', ['date'], unique=False)
    op.create_index('idx_user_daily_recommendations_user_date', 'user_daily_recommendations', ['user_id', 'date'], unique=False)
    op.create_table('user_radar_recommendations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('music_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_radar_recommendations')
    )
    op.create_index('idx_user_radar_recommendations_date', 'user_radar_recommendations', ['date'], unique=False)
    op.create_index('idx_user_radar_recommendations_user_date', 'user_radar_recommendations', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_radar_recommendations_user_date', table_name='user_radar_recommendations')
    op.drop_index('idx_user_radar_recommendations_date', table_name='user_radar_recommendations')
    op.drop_table('user_radar_recommendations')
    op.drop_index('idx_user_daily_recommendations_user_date', table_name='user_daily_recommendations')
    op.drop_index('idx_user_daily_recommendations_date', table_name='user_daily_recommendations')
    op.drop_table('user_daily_recommendations')
    # ### end Alembic commands ###
