"""add vector documents table

Revision ID: 2b6bb814a30f
Revises: 011206312bcb
Create Date: 2026-06-13 20:56:41.037746

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b6bb814a30f'
down_revision: Union[str, Sequence[str], None] = '011206312bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('vector_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('namespace', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_documents_namespace'), 'vector_documents', ['namespace'], unique=False)
    op.create_index('ix_vector_documents_namespace_created', 'vector_documents', ['namespace', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vector_documents_namespace_created', table_name='vector_documents')
    op.drop_index(op.f('ix_vector_documents_namespace'), table_name='vector_documents')
    op.drop_table('vector_documents')
    # ### end Alembic commands ###
