"""add_forward_count_to_music_album_playlist

Revision ID: 39c71a50067c
Revises: 45a5683e8a03
Create Date: 2026-06-12 22:50:55.386308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39c71a50067c'
down_revision: Union[str, Sequence[str], None] = '45a5683e8a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('forward_count', sa.BigInteger(), nullable=False))
    op.add_column('musics', sa.Column('forward_count', sa.BigInteger(), nullable=False))
    op.add_column('playlists', sa.Column('forward_count', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'forward_count')
    op.drop_column('musics', 'forward_count')
    op.drop_column('albums', 'forward_count')
    # ### end Alembic commands ###
