"""add_ai_conversations_table

Revision ID: 735845797c23
Revises: 2b6bb814a30f
Create Date: 2026-06-13 21:45:14.630479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735845797c23'
down_revision: Union[str, Sequence[str], None] = '2b6bb814a30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_conversations_thread_id', 'ai_conversations', ['thread_id'], unique=True)
    op.create_index('idx_ai_conversations_user_status_time', 'ai_conversations', ['user_id', 'status', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_conversations_user_status_time', table_name='ai_conversations')
    op.drop_index('idx_ai_conversations_thread_id', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
