"""add system_logs table

Revision ID: 9fd0a5c411bb
Revises: b7c9d2e4f6a8
Create Date: 2026-06-19 12:16:07.846215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9fd0a5c411bb'
down_revision: Union[str, Sequence[str], None] = 'b7c9d2e4f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('logger', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_system_logs_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_system_logs_level_created', 'system_logs', ['level', 'created_at'], unique=False)
    op.create_index('idx_system_logs_message_gin', 'system_logs', ['message'], unique=False, postgresql_using='gin', postgresql_ops={'message': 'gin_trgm_ops'})
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index('idx_system_logs_message_gin', table_name='system_logs', postgresql_using='gin', postgresql_ops={'message': 'gin_trgm_ops'})
    op.drop_index('idx_system_logs_level_created', table_name='system_logs')
    op.drop_index('idx_system_logs_created_at', table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
