"""add_play_count_to_play_history_and_user_style_language_preferences

Revision ID: c0eb926fd655
Revises: 39c71a50067c
Create Date: 2026-06-13 15:28:09.791603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0eb926fd655'
down_revision: Union[str, Sequence[str], None] = '39c71a50067c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_languages',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('language_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'language_id')
    )
    op.create_index('idx_user_languages_language_id', 'user_languages', ['language_id'], unique=False)
    op.create_table('user_styles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('style_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'style_id')
    )
    op.create_index('idx_user_styles_style_id', 'user_styles', ['style_id'], unique=False)
    op.add_column(
        'play_history',
        sa.Column('play_count', sa.Integer(), server_default=sa.text('1'), nullable=False)
    )
    op.create_check_constraint(
        'chk_play_history_play_count_positive',
        'play_history',
        'play_count >= 1'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_play_history_play_count_positive', 'play_history', type_='check')
    op.drop_column('play_history', 'play_count')
    op.drop_index('idx_user_styles_style_id', table_name='user_styles')
    op.drop_table('user_styles')
    op.drop_index('idx_user_languages_language_id', table_name='user_languages')
    op.drop_table('user_languages')
    # ### end Alembic commands ###
