"""remove cities table change user city to varchar

Revision ID: c85a4f26c4ef
Revises: d7f56266b3f3
Create Date: 2026-06-08 18:02:06.668303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85a4f26c4ef'
down_revision: Union[str, Sequence[str], None] = 'd7f56266b3f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('users_city_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_city_id_fkey'), 'users', 'cities', ['city_id'], ['id'])
    op.drop_column('users', 'city')
    op.create_table('cities',
    sa.Column('id', sa.SMALLINT(), server_default=sa.text("nextval('cities_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cities_pkey')),
    sa.UniqueConstraint('name', name=op.f('cities_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
