"""init_schema_and_seed_level_config

Revision ID: d7f56266b3f3
Revises: 
Create Date: 2026-06-07 12:43:13.760559

"""
import json
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f56266b3f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('albums',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('collect_count', sa.BigInteger(), nullable=False),
    sa.Column('play_count', sa.BigInteger(), nullable=False),
    sa.Column('hot', sa.SmallInteger(), nullable=False),
    sa.Column('cover_icon_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('collect_count >= 0', name='chk_albums_collect_count_nonnegative'),
    sa.CheckConstraint('hot >= 0 AND hot <= 1000', name='chk_albums_hot'),
    sa.CheckConstraint('play_count >= 0', name='chk_albums_play_count_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_albums_collect_count', 'albums', [sa.literal_column('collect_count DESC')], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('idx_albums_created_at', 'albums', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('idx_albums_hot', 'albums', [sa.literal_column('hot DESC')], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('idx_albums_play_count', 'albums', [sa.literal_column('play_count DESC')], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('idx_albums_title_trgm', 'albums', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_where=sa.text('is_deleted IS false'))
    op.create_table('cities',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('emotion_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('instruments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('interest_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('languages',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('level_config',
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('min_exp', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('level')
    )
    op.create_index('idx_level_config_min_exp', 'level_config', ['min_exp'], unique=False)
    op.create_table('styles',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('album_emotion_tags',
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('emotion_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emotion_tag_id'], ['emotion_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'emotion_tag_id')
    )
    op.create_index('idx_album_emotion_tags_tag', 'album_emotion_tags', ['emotion_tag_id'], unique=False)
    op.create_table('album_interest_tags',
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('interest_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interest_tag_id'], ['interest_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'interest_tag_id')
    )
    op.create_index('idx_album_interest_tags_tag', 'album_interest_tags', ['interest_tag_id'], unique=False)
    op.create_table('musics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('style_id', sa.SmallInteger(), nullable=True),
    sa.Column('language_id', sa.SmallInteger(), nullable=True),
    sa.Column('collect_count', sa.BigInteger(), nullable=False),
    sa.Column('hot', sa.SmallInteger(), nullable=False),
    sa.Column('comment_count', sa.BigInteger(), nullable=False),
    sa.Column('play_count', sa.BigInteger(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('lyrics_url', sa.String(length=500), nullable=True),
    sa.Column('cover_icon_url', sa.String(length=500), nullable=True),
    sa.Column('cover_home_url', sa.String(length=500), nullable=True),
    sa.Column('cover_play_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('collect_count >= 0', name='chk_musics_collect_count_nonnegative'),
    sa.CheckConstraint('comment_count >= 0', name='chk_musics_comment_count_nonnegative'),
    sa.CheckConstraint('hot >= 0 AND hot <= 1000', name='chk_musics_hot'),
    sa.CheckConstraint('play_count >= 0', name='chk_musics_play_count_nonnegative'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['styles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_musics_collect_count', 'musics', [sa.literal_column('collect_count DESC')], unique=False)
    op.create_index('idx_musics_created_at', 'musics', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_musics_hot', 'musics', [sa.literal_column('hot DESC')], unique=False)
    op.create_index('idx_musics_language_id', 'musics', ['language_id'], unique=False)
    op.create_index('idx_musics_play_count', 'musics', [sa.literal_column('play_count DESC')], unique=False)
    op.create_index('idx_musics_release_date', 'musics', [sa.literal_column('release_date DESC')], unique=False)
    op.create_index('idx_musics_style_id', 'musics', ['style_id'], unique=False)
    op.create_index('idx_musics_title_trgm', 'musics', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('safety_score', sa.SmallInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('city_id', sa.SmallInteger(), nullable=True),
    sa.Column('birth', sa.Date(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('banned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ban_duration', sa.Interval(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("ban_duration IS NULL OR ban_duration > INTERVAL '0'", name='chk_users_ban_duration_positive'),
    sa.CheckConstraint('(banned_at IS NULL AND status NOT IN (1, 2, 3)) OR (banned_at IS NOT NULL AND status IN (1, 2, 3))', name='chk_users_ban_consistency'),
    sa.CheckConstraint('ban_duration IS NULL OR banned_at IS NOT NULL', name='chk_users_ban_dates'),
    sa.CheckConstraint('exp >= 0', name='chk_users_exp_nonnegative'),
    sa.CheckConstraint('gender >= 0 AND gender <= 2', name='chk_users_gender'),
    sa.CheckConstraint('level >= 0', name='chk_users_level_nonnegative'),
    sa.CheckConstraint('like_count >= 0', name='chk_users_like_count_nonnegative'),
    sa.CheckConstraint('role >= 0 AND role <= 3', name='chk_users_role'),
    sa.CheckConstraint('safety_score >= 0 AND safety_score <= 10', name='chk_users_safety_score'),
    sa.CheckConstraint('status >= 0 AND status <= 3', name='chk_users_status'),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_banned_at', 'users', ['banned_at'], unique=False, postgresql_where=sa.text('banned_at IS NOT NULL'))
    op.create_index('idx_users_created_at', 'users', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('idx_users_exp', 'users', [sa.literal_column('exp DESC')], unique=False)
    op.create_index('idx_users_last_login_at', 'users', [sa.literal_column('last_login_at DESC')], unique=False)
    op.create_index('idx_users_level', 'users', ['level'], unique=False)
    op.create_index('idx_users_nickname_trgm', 'users', ['nickname'], unique=False, postgresql_using='gin', postgresql_ops={'nickname': 'gin_trgm_ops'})
    op.create_index('idx_users_phone', 'users', ['phone'], unique=True, postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_index('idx_users_status', 'users', ['status'], unique=False, postgresql_where=sa.text('is_deleted IS false'))
    op.create_index('idx_users_username_trgm', 'users', ['username'], unique=False, postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.create_table('album_authors',
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='chk_album_authors_ordinal_nonnegative'),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'author_id'),
    sa.UniqueConstraint('album_id', 'ordinal', name='uq_album_authors_ordinal')
    )
    op.create_index('idx_album_authors_author', 'album_authors', ['author_id'], unique=False)
    op.create_table('album_musics',
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='chk_album_musics_ordinal_nonnegative'),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'music_id'),
    sa.UniqueConstraint('album_id', 'ordinal', name='uq_album_musics_ordinal'),
    sa.UniqueConstraint('music_id', name='uq_album_musics_music')
    )
    op.create_table('music_authors',
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='chk_music_authors_ordinal_nonnegative'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('music_id', 'author_id'),
    sa.UniqueConstraint('music_id', 'ordinal', name='uq_music_authors_ordinal')
    )
    op.create_index('idx_music_authors_author', 'music_authors', ['author_id'], unique=False)
    op.create_table('music_emotion_tags',
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('emotion_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emotion_tag_id'], ['emotion_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('music_id', 'emotion_tag_id')
    )
    op.create_index('idx_music_emotion_tags_tag', 'music_emotion_tags', ['emotion_tag_id'], unique=False)
    op.create_table('music_instruments',
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('music_id', 'instrument_id')
    )
    op.create_index('idx_music_instruments_instrument', 'music_instruments', ['instrument_id'], unique=False)
    op.create_table('music_interest_tags',
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('interest_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_tag_id'], ['interest_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('music_id', 'interest_tag_id')
    )
    op.create_index('idx_music_interest_tags_tag', 'music_interest_tags', ['interest_tag_id'], unique=False)
    op.create_table('play_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_play_history_user_time', 'play_history', ['user_id', sa.literal_column('played_at DESC')], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('collect_count', sa.BigInteger(), nullable=False),
    sa.Column('play_count', sa.BigInteger(), nullable=False),
    sa.Column('hot', sa.SmallInteger(), nullable=False),
    sa.Column('comment_count', sa.BigInteger(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('cover_icon_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('collect_count >= 0', name='chk_playlists_collect_count_nonnegative'),
    sa.CheckConstraint('comment_count >= 0', name='chk_playlists_comment_count_nonnegative'),
    sa.CheckConstraint('hot >= 0 AND hot <= 1000', name='chk_playlists_hot'),
    sa.CheckConstraint('play_count >= 0', name='chk_playlists_play_count_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playlists_collect_count', 'playlists', [sa.literal_column('collect_count DESC')], unique=False)
    op.create_index('idx_playlists_created_at', 'playlists', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_playlists_hot', 'playlists', [sa.literal_column('hot DESC')], unique=False)
    op.create_index('idx_playlists_play_count', 'playlists', [sa.literal_column('play_count DESC')], unique=False)
    op.create_index('idx_playlists_title_trgm', 'playlists', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('idx_playlists_unique_user_like', 'playlists', ['user_id'], unique=True, postgresql_where=sa.text('is_like IS true'))
    op.create_index('idx_playlists_user_id', 'playlists', ['user_id'], unique=False)
    op.create_table('space_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('comment_count', sa.BigInteger(), nullable=False),
    sa.Column('forward_count', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(post_type = 'original' AND source_id IS NULL AND source_type IS NULL) OR (post_type = 'forward' AND source_id IS NOT NULL AND source_type IS NOT NULL)", name='chk_space_posts_source_consistency'),
    sa.CheckConstraint("post_type IN ('original', 'forward')", name='chk_space_posts_post_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_space_posts_created_at', 'space_posts', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('is_deleted IS false AND is_private IS false'))
    op.create_index('idx_space_posts_user_time', 'space_posts', ['user_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('is_deleted IS false AND is_private IS false'))
    op.create_table('user_album_collections',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'album_id')
    )
    op.create_index('idx_user_album_collections_user_time', 'user_album_collections', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_emotion_tags',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('emotion_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emotion_tag_id'], ['emotion_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'emotion_tag_id')
    )
    op.create_index('idx_user_emotion_tags_tag_id', 'user_emotion_tags', ['emotion_tag_id'], unique=False)
    op.create_table('user_follows',
    sa.Column('follower_id', sa.BigInteger(), nullable=False),
    sa.Column('followee_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_id <> followee_id', name='chk_user_follows_no_self_follow'),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_index('idx_user_follows_followee', 'user_follows', ['followee_id'], unique=False)
    op.create_index('idx_user_follows_followee_time', 'user_follows', ['followee_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_user_follows_follower_time', 'user_follows', ['follower_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_interest_tags',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('interest_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_tag_id'], ['interest_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'interest_tag_id')
    )
    op.create_index('idx_user_interest_tags_tag_id', 'user_interest_tags', ['interest_tag_id'], unique=False)
    op.create_table('user_music_collections',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'music_id')
    )
    op.create_index('idx_user_music_collections_user_time', 'user_music_collections', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('user_music_releases',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'music_id')
    )
    op.create_index('idx_user_music_releases_user_time', 'user_music_releases', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('music_id', sa.BigInteger(), nullable=True),
    sa.Column('playlist_id', sa.BigInteger(), nullable=True),
    sa.Column('space_post_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('root_id', sa.BigInteger(), nullable=True),
    sa.Column('is_nested_reply', sa.Boolean(), nullable=False),
    sa.Column('safety', sa.SmallInteger(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('like_count', sa.BigInteger(), nullable=False),
    sa.Column('dislike_count', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('(music_id IS NOT NULL)::int + (playlist_id IS NOT NULL)::int + (space_post_id IS NOT NULL)::int = 1', name='chk_comment_target_unique'),
    sa.CheckConstraint('safety >= 0 AND safety <= 10', name='chk_comments_safety'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_post_id'], ['space_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_music_root', 'comments', ['music_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('parent_id IS NULL AND is_deleted IS false'))
    op.create_index('idx_comments_playlist_root', 'comments', ['playlist_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('parent_id IS NULL AND is_deleted IS false'))
    op.create_index('idx_comments_root_time', 'comments', ['root_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_comments_space_root', 'comments', ['space_post_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text('parent_id IS NULL AND is_deleted IS false'))
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('playlist_emotion_tags',
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('emotion_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emotion_tag_id'], ['emotion_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'emotion_tag_id')
    )
    op.create_index('idx_playlist_emotion_tags_tag', 'playlist_emotion_tags', ['emotion_tag_id'], unique=False)
    op.create_table('playlist_interest_tags',
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('interest_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interest_tag_id'], ['interest_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'interest_tag_id')
    )
    op.create_index('idx_playlist_interest_tags_tag', 'playlist_interest_tags', ['interest_tag_id'], unique=False)
    op.create_table('playlist_musics',
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('music_id', sa.BigInteger(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='chk_playlist_musics_ordinal_nonnegative'),
    sa.ForeignKeyConstraint(['music_id'], ['musics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'music_id'),
    sa.UniqueConstraint('playlist_id', 'ordinal', name='uq_playlist_musics_ordinal')
    )
    op.create_table('space_post_images',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ordinal >= 0', name='chk_space_post_images_ordinal_nonnegative'),
    sa.ForeignKeyConstraint(['post_id'], ['space_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'ordinal')
    )
    op.create_table('space_post_likes',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['space_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_index('idx_space_post_likes_user', 'space_post_likes', ['user_id'], unique=False)
    op.create_table('user_playlist_collections',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('playlist_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'playlist_id')
    )
    op.create_index('idx_user_playlist_collections_user_time', 'user_playlist_collections', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('comment_dislikes',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_index('idx_comment_dislikes_user', 'comment_dislikes', ['user_id'], unique=False)
    op.create_table('comment_likes',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_index('idx_comment_likes_user', 'comment_likes', ['user_id'], unique=False)

    # Seed level_config data from the shared dictionary seed file
    seed_path = (
        Path(__file__).resolve().parent.parent.parent
        / "src"
        / "echomemory_backend"
        / "data"
        / "dictionary_seed.json"
    )
    with open(seed_path, encoding="utf-8") as f:
        seed_data = json.load(f)
    level_config_rows = seed_data.get("level_config", [])

    level_config_table = sa.table(
        'level_config',
        sa.column('level', sa.SmallInteger),
        sa.column('min_exp', sa.Integer),
        sa.column('title', sa.String),
    )
    op.bulk_insert(level_config_table, level_config_rows)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM level_config")
    op.drop_index('idx_comment_likes_user', table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index('idx_comment_dislikes_user', table_name='comment_dislikes')
    op.drop_table('comment_dislikes')
    op.drop_index('idx_user_playlist_collections_user_time', table_name='user_playlist_collections')
    op.drop_table('user_playlist_collections')
    op.drop_index('idx_space_post_likes_user', table_name='space_post_likes')
    op.drop_table('space_post_likes')
    op.drop_table('space_post_images')
    op.drop_table('playlist_musics')
    op.drop_index('idx_playlist_interest_tags_tag', table_name='playlist_interest_tags')
    op.drop_table('playlist_interest_tags')
    op.drop_index('idx_playlist_emotion_tags_tag', table_name='playlist_emotion_tags')
    op.drop_table('playlist_emotion_tags')
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.drop_index('idx_comments_space_root', table_name='comments', postgresql_where=sa.text('parent_id IS NULL AND is_deleted IS false'))
    op.drop_index('idx_comments_root_time', table_name='comments')
    op.drop_index('idx_comments_playlist_root', table_name='comments', postgresql_where=sa.text('parent_id IS NULL AND is_deleted IS false'))
    op.drop_index('idx_comments_music_root', table_name='comments', postgresql_where=sa.text('parent_id IS NULL AND is_deleted IS false'))
    op.drop_table('comments')
    op.drop_index('idx_user_music_releases_user_time', table_name='user_music_releases')
    op.drop_table('user_music_releases')
    op.drop_index('idx_user_music_collections_user_time', table_name='user_music_collections')
    op.drop_table('user_music_collections')
    op.drop_index('idx_user_interest_tags_tag_id', table_name='user_interest_tags')
    op.drop_table('user_interest_tags')
    op.drop_index('idx_user_follows_follower_time', table_name='user_follows')
    op.drop_index('idx_user_follows_followee_time', table_name='user_follows')
    op.drop_index('idx_user_follows_followee', table_name='user_follows')
    op.drop_table('user_follows')
    op.drop_index('idx_user_emotion_tags_tag_id', table_name='user_emotion_tags')
    op.drop_table('user_emotion_tags')
    op.drop_index('idx_user_album_collections_user_time', table_name='user_album_collections')
    op.drop_table('user_album_collections')
    op.drop_index('idx_space_posts_user_time', table_name='space_posts', postgresql_where=sa.text('is_deleted IS false AND is_private IS false'))
    op.drop_index('idx_space_posts_created_at', table_name='space_posts', postgresql_where=sa.text('is_deleted IS false AND is_private IS false'))
    op.drop_table('space_posts')
    op.drop_index('idx_playlists_user_id', table_name='playlists')
    op.drop_index('idx_playlists_unique_user_like', table_name='playlists', postgresql_where=sa.text('is_like IS true'))
    op.drop_index('idx_playlists_title_trgm', table_name='playlists', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_playlists_play_count', table_name='playlists')
    op.drop_index('idx_playlists_hot', table_name='playlists')
    op.drop_index('idx_playlists_created_at', table_name='playlists')
    op.drop_index('idx_playlists_collect_count', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('idx_play_history_user_time', table_name='play_history')
    op.drop_table('play_history')
    op.drop_index('idx_music_interest_tags_tag', table_name='music_interest_tags')
    op.drop_table('music_interest_tags')
    op.drop_index('idx_music_instruments_instrument', table_name='music_instruments')
    op.drop_table('music_instruments')
    op.drop_index('idx_music_emotion_tags_tag', table_name='music_emotion_tags')
    op.drop_table('music_emotion_tags')
    op.drop_index('idx_music_authors_author', table_name='music_authors')
    op.drop_table('music_authors')
    op.drop_table('album_musics')
    op.drop_index('idx_album_authors_author', table_name='album_authors')
    op.drop_table('album_authors')
    op.drop_index('idx_users_username_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'username': 'gin_trgm_ops'})
    op.drop_index('idx_users_status', table_name='users', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('idx_users_phone', table_name='users', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('idx_users_nickname_trgm', table_name='users', postgresql_using='gin', postgresql_ops={'nickname': 'gin_trgm_ops'})
    op.drop_index('idx_users_level', table_name='users')
    op.drop_index('idx_users_last_login_at', table_name='users')
    op.drop_index('idx_users_exp', table_name='users')
    op.drop_index('idx_users_email', table_name='users', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_index('idx_users_banned_at', table_name='users', postgresql_where=sa.text('banned_at IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('idx_musics_title_trgm', table_name='musics', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('idx_musics_style_id', table_name='musics')
    op.drop_index('idx_musics_release_date', table_name='musics')
    op.drop_index('idx_musics_play_count', table_name='musics')
    op.drop_index('idx_musics_language_id', table_name='musics')
    op.drop_index('idx_musics_hot', table_name='musics')
    op.drop_index('idx_musics_created_at', table_name='musics')
    op.drop_index('idx_musics_collect_count', table_name='musics')
    op.drop_table('musics')
    op.drop_index('idx_album_interest_tags_tag', table_name='album_interest_tags')
    op.drop_table('album_interest_tags')
    op.drop_index('idx_album_emotion_tags_tag', table_name='album_emotion_tags')
    op.drop_table('album_emotion_tags')
    op.drop_table('styles')
    op.drop_index('idx_level_config_min_exp', table_name='level_config')
    op.drop_table('level_config')
    op.drop_table('languages')
    op.drop_table('interest_tags')
    op.drop_table('instruments')
    op.drop_table('emotion_tags')
    op.drop_table('cities')
    op.drop_index('idx_albums_title_trgm', table_name='albums', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('idx_albums_play_count', table_name='albums', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('idx_albums_hot', table_name='albums', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('idx_albums_created_at', table_name='albums', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_index('idx_albums_collect_count', table_name='albums', postgresql_where=sa.text('is_deleted IS false'))
    op.drop_table('albums')
    # ### end Alembic commands ###
