"""add_notifications_messages_user_blocks_user_is_official

Revision ID: fdaf05e679b3
Revises: a3b8c1d2e4f5
Create Date: 2026-06-12 19:07:51.668162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdaf05e679b3'
down_revision: Union[str, Sequence[str], None] = 'a3b8c1d2e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user1_id', sa.BigInteger(), nullable=False),
    sa.Column('user2_id', sa.BigInteger(), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('user1_unread_count', sa.BigInteger(), nullable=False),
    sa.Column('user2_unread_count', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user1_id < user2_id', name='chk_conversations_user_order'),
    sa.CheckConstraint('user1_unread_count >= 0', name='chk_conversations_user1_unread_nonneg'),
    sa.CheckConstraint('user2_unread_count >= 0', name='chk_conversations_user2_unread_nonneg'),
    sa.ForeignKeyConstraint(['last_message_id'], ['direct_messages.id'], ondelete='SET NULL', use_alter=True, name='fk_conversations_last_message_id'),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='uq_conversations_user_pair')
    )
    op.create_index('idx_conversations_user1_time', 'conversations', ['user1_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_conversations_user2_time', 'conversations', ['user2_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('user', 'comment', 'space_post')", name='chk_notifications_target_type'),
    sa.CheckConstraint('actor_id IS NULL OR actor_id <> recipient_id', name='chk_notifications_no_self'),
    sa.CheckConstraint('type >= 0 AND type <= 4', name='chk_notifications_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notifications_recipient_time', 'notifications', ['recipient_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_notifications_recipient_unread', 'notifications', ['recipient_id'], unique=False, postgresql_where=sa.text('is_read IS false'))
    op.create_index('uq_notifications_dedupe_unread', 'notifications', ['recipient_id', 'actor_id', 'type', 'target_type', 'target_id'], unique=True, postgresql_where=sa.text('is_read = false'))
    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.BigInteger(), nullable=False),
    sa.Column('blocked_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocker_id <> blocked_id', name='chk_user_blocks_no_self'),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_index('idx_user_blocks_blocked', 'user_blocks', ['blocked_id'], unique=False)
    op.create_table('direct_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_direct_messages_conversation_time', 'direct_messages', ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_direct_messages_sender', 'direct_messages', ['sender_id'], unique=False)
    op.add_column(
        'users',
        sa.Column(
            'is_official',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )
    # 已有行回填完毕后移除 server_default，新行交由 ORM 默认值控制
    op.alter_column('users', 'is_official', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_official')
    op.drop_index('idx_direct_messages_sender', table_name='direct_messages')
    op.drop_index('idx_direct_messages_conversation_time', table_name='direct_messages')
    op.drop_table('direct_messages')
    op.drop_index('idx_user_blocks_blocked', table_name='user_blocks')
    op.drop_table('user_blocks')
    op.drop_index('uq_notifications_dedupe_unread', table_name='notifications', postgresql_where=sa.text('is_read = false'))
    op.drop_index('idx_notifications_recipient_unread', table_name='notifications', postgresql_where=sa.text('is_read IS false'))
    op.drop_index('idx_notifications_recipient_time', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_conversations_user2_time', table_name='conversations')
    op.drop_index('idx_conversations_user1_time', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
